export const methodsObject = [
  {
    method: "object.name",
    inputValue: "",
    inputType: null,
    contents: ["object.name;"],
    spec: "methods",
  },
  {
    method: "object.surname",
    inputValue: "",
    inputType: null,
    contents: ["object.surname;"],
    spec: "methods",
  },
  {
    method: "object.age",
    inputValue: "",
    inputType: null,
    contents: ["object.age;"],
    spec: "methods",
  },
  {
    method: "object.sayHello()",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["object.sayHello();"],
    spec: "methods",
  },
  {
    method: "object.getFullName()",
    inputValue: "",
    inputType: null,
    contents: ["object.getFullName();"],
    spec: "methods",
  },
  {
    method: "object.friend",
    inputValue: "",
    inputType: null,
    contents: ["object.friend;"],
    spec: "methods",
  },
  {
    method: "object['friend']['name']",
    inputValue: "",
    inputType: null,
    contents: ["object['friend']['name']"],
    spec: "methods",
  },
  {
    method: "object['friend']['surname']",
    inputValue: "",
    inputType: null,
    contents: ["object['friend']['surname']"],
    spec: "methods",
  },
  {
    method: "object['friend']['age']",
    inputValue: "",
    inputType: null,
    contents: ["object['friend']['age']"],
    spec: "methods",
  },
  {
    method: "object === exampleObject",
    inputValue: "",
    inputType: null,
    contents: ["object === exampleObject"],
    spec: "methods",
  },
  {
    method: "object.name === exampleObject.name",
    inputValue: "",
    inputType: null,
    contents: ["object.name === exampleObject.name"],
    spec: "methods",
  },
  {
    method: "object.friend === exampleObject.friend",
    inputValue: "",
    inputType: null,
    contents: ["object.friend === exampleObject.friend"],
    spec: "methods",
  },
  {
    method: "object.name = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object.name = "],
    spec: "methods",
  },
  {
    method: "object.surname = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object.surname = "],
    spec: "methods",
  },
  {
    method: "object.age = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object.age = "],
    spec: "methods",
  },
  {
    method: "object.city = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object.city = "],
    spec: "methods",
  },
  {
    method: "object['friend']['name'] = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object['friend']['name'] = "],
    spec: "methods",
  },
  {
    method: "object['friend']['surname'] = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object['friend']['surname'] = "],
    spec: "methods",
  },
  {
    method: "object['friend']['age'] = ",
    inputValue: "",
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+)$/,
    contents: [],
    additionalContents: ["object['friend']['age'] = "],
    spec: "methods",
  },
  {
    method: "for...in",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["for ( const property in object) {", "console.log(`${property}: ${object[property]}`)", "}"],
    spec: "iteration",
  },
  {
    method: "const { name, surname, ...rest } = object",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["const { name, surname, ...objectWithoutNameAndSurname } = object;",
      "console.log(name, surname)"],
    spec: "destructuring",
  },
  {
    method: "const { city = 'N/A' } = object",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["const { city = 'N/A' } = object;",
      "console.log(city)"],
    spec: "destructuring",
  },
  {
    method: "const { surname: lastName } = object",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["const { surname: lastName } = object;",
      "console.log(lastName)"],
    spec: "destructuring",
  },
  {
    method: "const { friend: { name: friendName } } = object",
    inputValue: "",
    inputType: null,
    contents: [],
    additionalContents: ["const { friend: { name: friendName } } = object;",
      "console.log(friendName)"],
    spec: "destructuring",
  },
  {
    method: "function argument destructuring",
    inputValue: "",
    inputType: null,
    contents: ["getObjectFullNameWithAge(object)"],
    additionalContents: ["const getObjectFullNameWithAge = ({ name, surname, age }) => `${name} ${surname} ${age}`;"],
    spec: "destructuring",
  },
  {
    method: "cloning an object (shallow copy)",
    inputValue: "",
    inputType: null,
    contents: ["{ ...object };"],
    spec: "spreadSyntax",
  },
  {
    method: "merging objects",
    inputValue: "",
    inputType: null,
    contents: ["{ ...object, ...additionalObject };"],
    additionalContents: ["const additionalObject = {", "city: 'New York',", "hobby: 'swimming',", "}"],
    spec: "spreadSyntax",
  },
  {
    method: "adding properties to an object",
    inputValue: "",
    inputType: null,
    contents: ["{ ...object, city: 'N/A' }"],
    spec: "immutability",
  },
  {
    method: "editing object properties",
    inputValue: "",
    inputType: null,
    contents: ["{ ...object, name: 'Tom' }"],
    spec: "immutability",
  },
  {
    method: "removal of object's property",
    inputValue: "",
    inputType: null,
    contents: ["rest"],
    additionalContents: ["const { age, ...rest } = object"],
    spec: "immutability",
  },
];