export const methodsArrayRaw = [
  {
    method: "pop",
    inputType: null,
    contents: ["pop"],
    contentsWithButtons: [],
    spec: "methods",
  },
  {
    method: "shift",
    contents: ["shift"],
    contentsWithButtons: [],
    inputType: null,
    spec: "methods",
  },
  {
    method: "reverse",
    contents: ["reverse"],
    contentsWithButtons: [],
    inputType: null,
    spec: "methods",
  },
  {
    method: "push",
    contents: ["push"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "unshift",
    contents: ["unshift"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "join",
    contents: ["join"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^$|^("[^"]*"|\-?\d+)$/,
    spec: "methods",
  },
  {
    method: "slice",
    contents: ["slice"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^\s*-?\d+(\s*,\s*-?\d+\s*)?$/,
    spec: "methods",
  },
  {
    method: "includes",
    contents: ["includes"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "indexOf",
    contents: ["indexOf"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "lastIndexOf",
    contents: ["lastIndexOf"],
    contentsWithButtons: [],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "map",
    contents: ["map"],
    contentsWithButtons: [
      {
        button: "(a=>a*?)",
        content: "a => a * ",
        destiny: "forAll",
      },
      {
        button: "(a=>a**?)",
        content: "a => a ** ",
        destiny: "forAll",
      },
      {
        button: "(a=>a+?)",
        content: "a => a + ",
        destiny: "forAll",
      },
      {
        button: "(a=>a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>({...a,value:?}))",
        content: "a => ({ ...a, value: ",
        destiny: "forObjects",
      },
      {
        button: "(a=>({...a,name:?}))",
        content: "a => ({ ...a, name: ",
        destiny: "forObjects",
      },
      {
        button: "(a=>({...a,over:a.age>?}))",
        content: "a => ({ ...a, over: a.age >  ",
        destiny: "forObjects",
      },
      {
        button: "(a=>([...a,?]))",
        content: "a => ([ ...a, ",
        destiny: "forArrays",
      },
      {
        button: "(a=>([...a,a[0]=?]))",
        content: "a => ([ ...a, a[0] = ",
        destiny: "forArrays",
      },
      {
        button: "(a=>([...a,a[0]+?]))",
        content: "a => ([ ...a, a[0] + ",
        destiny: "forArrays",
      },
      {
        button: "(a=>([a[0],?]))",
        content: "a => ([a[0], ",
        destiny: "forArrays",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "find",
    contents: ["find"],
    contentsWithButtons: [
      {
        button: "(a=>a.length>?)",
        content: "a => a.length > ",
        destiny: "forAll",
      },
      {
        button: "(a=>a>?)",
        content: "a => a > ",
        destiny: "forAll",
      },
      {
        button: "(a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a%2===?)",
        content: "a => a % 2 === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a.name===?)",
        content: "a => a.name === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age===?)",
        content: "a => a.age === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age>?)",
        content: "a => a.age > ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
      {
        button: "(a=>a.find(e=>e===?))",
        content: "a => a.find( e => e === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "findIndex",
    contents: ["findIndex"],
    contentsWithButtons: [
      {
        button: "(a=>a.length>?)",
        content: "a => a.length > ",
        destiny: "forAll",
      },
      {
        button: "(a=>a>?)",
        content: "a => a > ",
        destiny: "forAll",
      },
      {
        button: "(a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a!==?)",
        content: "a => a !== ",
        destiny: "forAll",
      },
      {
        button: "(a=>a%2===?)",
        content: "a => a % 2 === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a.name===?)",
        content: "a => a.name === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age===?)",
        content: "a => a.age === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age>?)",
        content: "a => a.age > ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "filter",
    contents: ["filter"],
    contentsWithButtons: [
      {
        button: "(a=>a.length>?)",
        content: "a => a.length > ",
        destiny: "forAll",
      },
      {
        button: "(a=>a>?)",
        content: "a => a > ",
        destiny: "forAll",
      },
      {
        button: "(a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a!==?)",
        content: "a => a !== ",
        destiny: "forAll",
      },
      {
        button: "(a=>a%2===?)",
        content: "a => a % 2 === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a.name===?)",
        content: "a => a.name === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age===?)",
        content: "a => a.age === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age>?)",
        content: "a => a.age > ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "some",
    contents: ["some"],
    contentsWithButtons: [
      {
        button: "(a=>a.length>?)",
        content: "a => a.length > ",
        destiny: "forAll",
      },
      {
        button: "(a=>a>?)",
        content: "a => a > ",
        destiny: "forAll",
      },
      {
        button: "(a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a!==?)",
        content: "a => a !== ",
        destiny: "forAll",
      },
      {
        button: "(a=>a%2===?)",
        content: "a => a % 2 === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a.name===?)",
        content: "a => a.name === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age===?)",
        content: "a => a.age === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age>?)",
        content: "a => a.age > ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "every",
    contents: ["every"],
    contentsWithButtons: [
      {
        button: "(a=>a.length>?)",
        content: "a => a.length > ",
        destiny: "forAll",
      },
      {
        button: "(a=>a>?)",
        content: "a => a > ",
        destiny: "forAll",
      },
      {
        button: "(a=?)",
        content: "a => a = ",
        destiny: "forAll",
      },
      {
        button: "(a=>a===?)",
        content: "a => a === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a!==?)",
        content: "a => a !== ",
        destiny: "forAll",
      },
      {
        button: "(a=>a%2===?)",
        content: "a => a % 2 === ",
        destiny: "forAll",
      },
      {
        button: "(a=>a.name===?)",
        content: "a => a.name === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age===?)",
        content: "a => a.age === ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a.age>?)",
        content: "a => a.age > ",
        destiny: "forObjects",
      },
      {
        button: "(a=>a[0]===?)",
        content: "a => a[0] === ",
        destiny: "forArrays",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined)$/,
    spec: "methods",
  },
  {
    method: "reduce",
    contents: ["reduce"],
    contentsWithButtons: [
      {
        button: "((acc,cur)=>acc+cur,?)",
        content: "(acc, cur) => acc + cur ",
        destiny: "forAll",
      },
    ],
    inputType: "text",
    inputPattern: /^("[^"]*"|\-?\d+|null|false|true|NaN|undefined|)$/,
    spec: "methods",
  },
  {
    method: "sort",
    contents: ["sort"],
    contentsWithButtons: [
      {
        button: "( )",
        content: "",
        destiny: "forAll",
      },
      {
        button: "((a,b)=>a-b)",
        content: "(a,b) => a - b ",
        destiny: "forNumbers",
      },
      {
        button: "((a,b)=>b-a)",
        content: "(a,b) => b - a ",
        destiny: "forNumbers",
      },
      {
        button: "((a,b)=>a.localeCompare(b))",
        content: "(a,b) => a.localeCompare(b) ",
        destiny: "forStrings",
      },
      {
        button: "((a,b)=>b.localeCompare(a))",
        content: "(a,b) => b.localeCompare(a) ",
        destiny: "forStrings",
      },
      {
        button: "((a,b)=>a.name.localeCompare(b.name))",
        content: "(a,b) => a.name.localeCompare(b.name)",
        destiny: "forObjects",
      },
      {
        button: "((a,b)=>b.name.localeCompare(a.name))",
        content: "(a,b) => b.name.localeCompare(a.name) ",
        destiny: "forObjects",
      },
      {
        button: "((a,b)=>a.age-b.age)",
        content: "(a,b) => a.age - b.age ",
        destiny: "forObjects",
      },
      {
        button: "((a,b)=>b.age-a.age)",
        content: "(a,b) => b.age - a.age ",
        destiny: "forObjects",
      },
      {
        button: "((a,b)=>a[0].localeCompare(b[0]))",
        content: "(a,b) => a[0].localeCompare(b[0]) ",
        destiny: "forArrays",
      },
      {
        button: "((a,b)=>b[0].localeCompare(a[0]))",
        content: "(a,b) => b[0].localeCompare(a[0]) ",
        destiny: "forArrays",
      },
    ],
    inputType: null,
    spec: "methods",
  },

  
  {
    method: "cloning an array (shallow copy)",
    contents: ["...array"],
    contentsWithButtons: [],
    inputType: null,
    spec: "spreadSyntax",
  },
  {
    method: "merging arrays",
    contents: ["...array, ...exampleArray"],
    contentsWithButtons: [],
    inputType: null,
    spec: "spreadSyntax",
  },


  {
    method: "adding an element to an array",
    contents: [],
    contentsWithButtons: [
      {
        button: "[...array, 100]",
        content: "[...array, 100]",
        destiny: "forAll",
      },
      {
        button: "[...array, -20]",
        content: "[...array, -20]",
        destiny: "forAll",
      },
      {
        button: "[...array, 'text']",
        content: "[...array, 'text']",
        destiny: "forAll",
      },
      {
        button: "[...array, [1, 2, 3]]",
        content: "[...array, [ 1, 2, 3]]",
        destiny: "forAll",
      },
      {
        button: "[...array, { city: 'N/A' }]",
        content: "[...array, { city: 'N/A' }]",
        destiny: "forAll",
      },
    ],
    inputType: null,
    spec: "immutability",
  },
  {
    method: "editing an element of an array",
    inputType: "range",
    contents: ["...array.slice(0,editIndex),",
    "{ ...array[editIndex], age: 30 }",
    "...array.slice(editIndex + 1)"],
    contentsWithButtons: [],
    additionalContents: [],
    spec: "immutability",
  },

  //  stworzyć addEvent do removeIndex na wspólnym InptutType === "range"
  {
    method: "removing an element from an array",
    inputType: null,
    contents: ["...array.slice(0,removeIndex),", "...array.slice(removeIndex + 1)"],
    contentsWithButtons: [],
    additionalContents: [],
    spec: "immutability",
  },
  {
    method: "for...of",
    inputType: null,
    contents: [],
    contentsWithButtons: [],
    additionalContents: ["for (const element in array) {", "console.log(element)", "}"],
    spec: "iteration",
  },
  {
    method: "forEach",
    inputType: null,
    contents: [],
    contentsWithButtons: [],
    additionalContents: ["array.forEach((element, index) => {", "console.log(`${index  + 1}. ${element}`)", "})"],
    spec: "iteration",
  },
  {
    method: "const [element_1, element_2] = array",
    inputType: null,
    contents: [],
    contentsWithButtons: [],
    additionalContents: ["const [element_1, element_2] = array;",
      "console.log(element_1, element_2)"],
    spec: "destructuring",
  },
  {
    method: "const [element_1, ,element_3 = 0] = array",
    inputType: null,
    contents: [],
    contentsWithButtons: [],
    additionalContents: ["const [element_1, ,element_3 = 0] = array;",
      "console.log(element_3)"],
    spec: "destructuring",
  },
  {
    method: "const [element_1, element_2, ...rest] = array",
    inputType: null,
    contents: [],
    contentsWithButtons: [],
    additionalContents: ["const [element_1, element_2, ...rest] = array;",
      "console.log(rest)"],
    spec: "destructuring",
  },
];