export const exampleString = " This is an example 'string'";

export const letters = "abcdefghijklmnopqrstuvwxyz";

export const wordsArray = [
  "apple", "banana", "cherry", "date", "eggplant", "fig", "grape", "jackfruit", "kiwi", "lemon", "mango", "nectarine", "orange", "peach", "quince", "raspberry", "strawberry", "tangerine", "vanilla", "watermelon", "xylophone", "yellow", "zebra", "almond", "blackberry", "coconut", "dragonfruit", "elderberry", "fig", "grapefruit", "huckleberry", "kiwi", "lemon", "mango", "nectarine", "olive", "pineapple", "quince", "raspberry", "strawberry", "tangerine", "vanilla", "watermelon", "zucchini", "apricot", "blueberry", "cantaloupe", "date", "egg", "fig", "grape", "honeydew", "jackfruit", "kiwano", "lemon", "mulberry", "nectarine", "orange", "persimmon", "quince", "raspberry", "strawberry", "watermelon", "avocado", "carrot", "dill", "eggplant", "fennel", "grapefruit", "hazelnut", "jalapeno", "kale", "leek", "mushroom", "napa cabbage", "okra", "parsnip", "quinoa", "radish", "spinach", "thyme", "umami", "watercress", "xigua", "yam", "zucchini", "artichoke", "beetroot", "celery", "endive", "grapefruit", "horseradish", "jicama", "kohlrabi", "lemon", "nopales", "okra", "pea", "scallion", "vanilla", "wasabi", "zucchini", "black", "blue", "brown", "cyan", "gold", "gray", "green", "indigo", "lavender", "magenta", "maroon", "olive", "orange", "pink", "purple", "red", "teal", "turquoise", "violet", "white", "yellow", "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"
];

export const sentencesArray = [
  "The sun is shining.",
  "I like to eat pizza.",
  "She plays the guitar.",
  "He is a good friend.",
  "They went to the beach.",
  "We enjoy watching movies.",
  "The cat is sleeping on the mat.",
  "I have a big bookshelf.",
  "He drinks coffee every morning.",
  "She is wearing a beautiful dress.",
  "They are going on vacation.",
  "We visited a museum yesterday.",
  "The dog loves to chase balls.",
  "He plays soccer on weekends.",
  "She enjoys listening to music.",
  "They went for a long walk.",
  "We had a delicious dinner.",
  "The bird is singing in the tree.",
  "I need to buy groceries.",
  "He studies at the university.",
  "She likes to swim in the pool.",
  "They are watching a movie.",
  "We are planning a party.",
  "The car is parked in the garage.",
  "I woke up early this morning.",
  "He writes poems in his free time.",
  "She likes to dance salsa.",
  "They went shopping for clothes.",
  "We had a fun day at the amusement park.",
  "The rain is falling heavily.",
  "I have a lot of homework to do.",
  "He plays the piano beautifully.",
  "She is a talented artist.",
  "They are learning a new language.",
  "We went hiking in the mountains.",
  "The baby is sleeping peacefully.",
  "I enjoy reading books.",
  "He works as a teacher.",
  "She likes to bake cookies.",
  "They are going to a concert.",
  "We had a great time at the party.",
  "The train is arriving at the station.",
  "I want to travel the world.",
  "He volunteers at a local shelter.",
  "She is studying for an exam.",
  "They are playing a board game.",
  "We watched a beautiful sunset.",
  "The coffee tastes delicious.",
  "I need to do laundry.",
  "He is a talented singer.",
  "She enjoys gardening in her backyard.",
  "They went to the zoo.",
  "We had a picnic in the park."
];